//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GathererRipper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GathererRipper.SQLResources", typeof(SQLResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Card(MultiverseId, BaseMultiverseId, Part, Name, ManaCost, ConvertedManaCost, SetName, Text, FlavorText, Power, Toughness, RarityId, Number, Variant, Artist, LanguageId) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);.
        /// </summary>
        internal static string AddCard {
            get {
                return ResourceManager.GetString("AddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Card{0}(CardBaseMultiverseId, CardPart, CardVariant, CardLanguageId, {0}) VALUES (?, ?, ?, ?, ?);.
        /// </summary>
        internal static string AddCardTag {
            get {
                return ResourceManager.GetString("AddCardTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO {0}(Id, Name) VALUES (COALESCE((SELECT MAX(Id) FROM {0}), -1) + 1, ?);.
        /// </summary>
        internal static string AddEnumTable {
            get {
                return ResourceManager.GetString("AddEnumTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Set_(Name, NumberOfCards) VALUES (?, ?);.
        /// </summary>
        internal static string AddSet {
            get {
                return ResourceManager.GetString("AddSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Set_ SET NumberOfCards=? WHERE Name=?;.
        /// </summary>
        internal static string CorrectSet {
            get {
                return ResourceManager.GetString("CorrectSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS CardType (
        ///	CardBaseMultiverseId INTEGER NOT NULL,
        ///	CardPart             VARCHAR(128) NOT NULL,
        ///	CardVariant          CHARACTER(1),
        ///	CardLanguageId       INTEGER NOT NULL,
        ///	Type                 VARCHAR(64),
        ///
        ///	PRIMARY KEY(CardBaseMultiverseId, CardPart, CardVariant, CardLanguageId, Type),
        ///	FOREIGN KEY(CardBaseMultiverseId) REFERENCES Card(BaseMultiverseId),
        ///	FOREIGN KEY(CardPart) REFERENCES Card(Part),
        ///	FOREIGN KEY(CardVariant) REFERENCES Card(Variant),
        ///	FOREIGN KEY(Card [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DatabaseSchema {
            get {
                return ResourceManager.GetString("DatabaseSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Card WHERE BaseMultiverseId=? AND Part=? AND LanguageId=?.
        /// </summary>
        internal static string GetCardWithoutVariant {
            get {
                return ResourceManager.GetString("GetCardWithoutVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id FROM {0} WHERE Name=?;.
        /// </summary>
        internal static string GetEnumTableId {
            get {
                return ResourceManager.GetString("GetEnumTableId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT NumberOfCards, (SELECT COUNT(*) FROM Card JOIN Language ON Card.LanguageId = Language.Id WHERE Card.SetName=? AND Language.Name=&quot;Oracle&quot;) AS DownloadedCardNumber FROM Set_ WHERE Set_.Name=?;.
        /// </summary>
        internal static string GetTotalAndDownloadedSetCardsNumber {
            get {
                return ResourceManager.GetString("GetTotalAndDownloadedSetCardsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 1 FROM Card JOIN Language ON Card.LanguageId = Language.Id WHERE Card.BaseMultiverseId=? AND Card.Part = ? AND Language.Name=&quot;Oracle&quot;;.
        /// </summary>
        internal static string IsCardFullyDownloaded {
            get {
                return ResourceManager.GetString("IsCardFullyDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Name FROM Set_ WHERE Name=?;.
        /// </summary>
        internal static string SetExists {
            get {
                return ResourceManager.GetString("SetExists", resourceCulture);
            }
        }
    }
}
